In [1]:
import numpy as np

In [1]:
from numpy import genfromtxt

In [3]:
df = genfromtxt('data_banknote.txt' , delimiter=',')
df

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
label=df[:,4]

In [6]:
label

array([0., 0., 0., ..., 1., 1., 1.])

In [11]:
features=df[:,0:4]

In [12]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [17]:
X=features
y=label

In [18]:
from sklearn.model_selection import train_test_split

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X , y, test_size=0.2, random_state=42)

In [22]:
from sklearn.preprocessing import MinMaxScaler

In [23]:
scaler_object=MinMaxScaler()

In [24]:
scaler_object.fit(X_train)

MinMaxScaler()

In [25]:
scaled_X_train=scaler_object.transform(X_train)

In [26]:
scaled_X_train

array([[4.07704678e-01, 9.83199063e-01, 2.56697443e-01, 9.33178971e-02],
       [7.07908761e-01, 7.71971248e-01, 1.80872580e-01, 8.05140280e-01],
       [1.98559159e-01, 2.21136252e-01, 7.37428144e-01, 6.20911798e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [27]:
X_train

array([[-1.3885  , 12.5026  ,  0.69118 , -7.5487  ],
       [ 2.7744  ,  6.8576  , -1.0671  ,  0.075416],
       [-4.2887  , -7.8633  , 11.8387  , -1.8978  ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [28]:
scaled_X_test=scaler_object.transform(X_test)

In [29]:
scaled_X_train.min()

0.0

In [31]:
!pip install keras

In [34]:
from keras.models import Sequential
from keras.layers import Dense 

In [35]:
models=Sequential()

In [37]:
#first hidden layer
models.add(Dense(4 , input_dim=4 , activation='relu'))


#second hidden layer
models.add(Dense(8 , activation='relu'))


#output layer

models.add(Dense(1 , activation='sigmoid'))

C:\Users\hinaa\Anaconda3\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [38]:
models.compile(loss="binary_crossentropy", optimizer='adam', metrics=['accuracy'])

In [68]:
models.fit(scaled_X_train, y_train, epochs=55, verbose=1)

Epoch 1/55
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9797 - loss: 0.0601
Epoch 2/55
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9787 - loss: 0.0602
Epoch 3/55
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9815 - loss: 0.0524
Epoch 4/55
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9792 - loss: 0.0557
Epoch 5/55
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9818 - loss: 0.0559
Epoch 6/55
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9789 - loss: 0.0599
Epoch 7/55
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9846 - loss: 0.0534
Epoch 8/55
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9745 - loss: 0.0591
Epoch 9/55
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9854 - loss: 0.0491
Epoch 10/55
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9770 - loss: 0.0593
Epoch 11/55
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9816 - loss: 0.0503
Epoch 12/55
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9821 - lo

In [70]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.75753773, 0.34889447, 0.37966768, 0.81250432],
       [0.48778747, 0.82175665, 0.09174727, 0.56211079],
       [0.70853615, 0.92621058, 0.07349701, 0.38693083]])

In [71]:
prediction=models.predict(scaled_X_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


In [72]:
prediction

array([[8.09206278e-04],
       [3.47535014e-01],
       [1.01819895e-01],
       [5.01363247e-04],
       [7.58039881e-04],
       [5.99277089e-04],
       [1.73533603e-03],
       [3.22058069e-04],
       [5.97341626e-04],
       [4.87579848e-04],
       [9.09422636e-01],
       [9.97773945e-01],
       [7.60970521e-04],
       [9.69065726e-01],
       [7.20506255e-03],
       [7.45971680e-01],
       [9.93152738e-01],
       [9.94779944e-01],
       [7.85165429e-01],
       [9.28782046e-01],
       [5.78511739e-04],
       [3.62651306e-04],
       [9.64839339e-01],
       [3.45789769e-04],
       [9.99927759e-01],
       [4.00230463e-04],
       [2.41017391e-04],
       [9.85731483e-01],
       [2.61797133e-04],
       [1.65713616e-04],
       [9.95760620e-01],
       [8.93469842e-04],
       [3.94576462e-03],
       [9.99802649e-01],
       [9.99683559e-01],
       [3.04494548e-04],
       [8.75992060e-01],
       [9.93797183e-01],
       [9.98441041e-01],
       [5.37966669e-04],


In [73]:
import numpy as np
predicted_class=np.where(prediction > 0.5 , 1 ,0)
predicted_class

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [74]:
models.metrics_names

['loss', 'compile_metrics']

In [75]:
models.evaluate (x=scaled_X_test, y=y_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9858 - loss: 0.0451 


[0.04814856871962547, 0.9781818389892578]

In [76]:
from sklearn.metrics import classification_report, confusion_matrix

In [77]:
confusion_matrix(y_test, predicted_class)

array([[144,   4],
       [  2, 125]], dtype=int64)

In [78]:
print(classification_report(y_test, predicted_class))

              precision    recall  f1-score   support

         0.0       0.99      0.97      0.98       148
         1.0       0.97      0.98      0.98       127

    accuracy                           0.98       275
   macro avg       0.98      0.98      0.98       275
weighted avg       0.98      0.98      0.98       275

